import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import SessionProvider from "@/components/SessionProvider";
import NavBar from "@/components/NavBar";
import { authOptions } from "@/utils/auth/authOptions";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <SessionProvider session={session}>
        <body className="min-h-screen grid grid-rows-[auto_1fr] w-full">
          <NavBar />
          <main className="px-2">{children}</main>
        </body>
      </SessionProvider>
    </html>
  );
}
